name: CI

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: CI on python${{ matrix.python }} via ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: pip install tox
      - name: Run flake8
        run: tox -e flake8
